2020-08-25 15:51:19,643 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 15:51:44,685 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\login\views.py changed, reloading.
2020-08-25 15:51:44,687 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 15:51:47,076 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 15:52:16,651 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\login\views.py changed, reloading.
2020-08-25 15:52:16,653 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 15:52:19,168 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 15:52:33,756 django.request ERROR    Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lxmpt_p\Lek\login\views.py", line 29, in login_page
    logger.error(username, "auth in system!")
NameError: name 'logger' is not defined
2020-08-25 15:53:27,699 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\login\views.py changed, reloading.
2020-08-25 15:53:27,708 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 15:53:30,399 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 15:53:33,888 django.security.csrf WARNING  Forbidden (CSRF token missing or incorrect.): /
2020-08-25 15:54:46,511 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 15:54:51,371 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 15:55:27,660 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\login\views.py changed, reloading.
2020-08-25 15:55:27,662 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 15:55:29,008 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 15:55:33,631 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 15:55:44,468 login.views  ERROR    auth in system!
2020-08-25 15:56:17,158 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\login\views.py changed, reloading.
2020-08-25 15:56:17,160 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 15:56:19,227 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 15:56:23,718 login.views  ERROR    adminauth in system!
2020-08-25 15:56:41,888 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\login\views.py changed, reloading.
2020-08-25 15:56:41,890 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 15:56:44,317 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 15:57:06,873 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\login\views.py changed, reloading.
2020-08-25 15:57:06,876 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 15:57:08,897 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 15:57:17,902 login.views  INFO     admin auth in system!
2020-08-25 15:58:29,620 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\createRequest\views.py changed, reloading.
2020-08-25 15:58:29,622 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 15:58:31,806 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 15:59:40,706 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\createRequest\views.py changed, reloading.
2020-08-25 15:59:40,708 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 15:59:42,889 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:00:47,422 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\createRequest\views.py changed, reloading.
2020-08-25 16:00:47,424 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:00:49,287 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:00:52,076 django.request WARNING  Not Found: //profile
2020-08-25 16:01:16,029 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\createRequest\views.py changed, reloading.
2020-08-25 16:01:16,032 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:01:18,049 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:02:05,079 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\createRequest\views.py changed, reloading.
2020-08-25 16:02:05,081 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:02:07,274 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:02:08,075 createRequest.views INFO     admin open createRequestMki page!
2020-08-25 16:02:16,371 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\createRequest\views.py changed, reloading.
2020-08-25 16:02:16,373 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:02:18,730 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:02:19,265 createRequest.views INFO     admin open createRequest page!
2020-08-25 16:05:55,442 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\infoRequest\views.py changed, reloading.
2020-08-25 16:05:55,444 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:05:57,615 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:06:31,090 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\infoRequest\views.py changed, reloading.
2020-08-25 16:06:31,092 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:06:33,038 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:06:48,305 infoRequest.views INFO     admin DELETE request to create research with ID = 3
2020-08-25 16:08:52,889 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\listForRegistration\views.py changed, reloading.
2020-08-25 16:08:52,891 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:08:54,905 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:09:17,542 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\listForRegistration\views.py changed, reloading.
2020-08-25 16:09:17,544 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:09:19,499 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:09:25,326 createRequest.views INFO     admin open createRequest page!
2020-08-25 16:09:33,443 django.request ERROR    Internal Server Error: /listForRegistration/
Traceback (most recent call last):
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lxmpt_p\Lek\listForRegistration\views.py", line 110, in listForRegistrationPage
    logger.info(str(request.user.username) + " ACCEPT user request from registration with username =", + req[1])
TypeError: bad operand type for unary +: 'str'
2020-08-25 16:09:54,849 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\listForRegistration\views.py changed, reloading.
2020-08-25 16:09:54,851 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:09:56,860 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:09:58,182 django.request ERROR    Internal Server Error: /listForRegistration/
Traceback (most recent call last):
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: listForRegistration_registeredusers.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lxmpt_p\Lek\listForRegistration\views.py", line 91, in listForRegistrationPage
    user = User.objects.create_user(username=req[1],
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\models.py", line 147, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\models.py", line 141, in _create_user
    user.save(using=self._db)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\base.py", line 782, in save_base
    updated = self._save_table(
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\base.py", line 924, in _do_insert
    return manager._insert(
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\models\sql\compiler.py", line 1392, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: listForRegistration_registeredusers.username
2020-08-25 16:10:05,421 django.request ERROR    Internal Server Error: /listForRegistration/
Traceback (most recent call last):
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lxmpt_p\Lek\listForRegistration\views.py", line 116, in listForRegistrationPage
    logger.info(str(request.user.username) + " DELETE user request from registration with username =", + str(req[1]))
IndexError: string index out of range
2020-08-25 16:10:26,447 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\listForRegistration\views.py changed, reloading.
2020-08-25 16:10:26,449 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:10:28,635 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:10:29,388 django.request ERROR    Internal Server Error: /listForRegistration/
Traceback (most recent call last):
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lxmpt_p\Lek\listForRegistration\views.py", line 116, in listForRegistrationPage
    logger.info(str(request.user.username) + " DELETE user request from registration with username =" + str(req[1]))
IndexError: string index out of range
2020-08-25 16:10:33,905 django.request ERROR    Internal Server Error: /listForRegistration/
Traceback (most recent call last):
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\lxmpt_p\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\lxmpt_p\Lek\listForRegistration\views.py", line 116, in listForRegistrationPage
    logger.info(str(request.user.username) + " DELETE user request from registration with username =" + str(req[1]))
IndexError: string index out of range
2020-08-25 16:11:16,018 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\listForRegistration\views.py changed, reloading.
2020-08-25 16:11:16,020 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:11:18,081 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:12:38,318 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\listForRegistration\views.py changed, reloading.
2020-08-25 16:12:38,320 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:12:40,361 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-25 16:12:40,988 listForRegistration.views INFO     admin DELETE user request from registration
2020-08-25 16:13:06,098 django.utils.autoreload INFO     C:\Users\lxmpt_p\Lek\listForRegistration\views.py changed, reloading.
2020-08-25 16:13:06,099 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-25 16:13:08,216 django.utils.autoreload INFO     Watching for file changes with StatReloader
2020-08-26 02:52:17,033 asyncio      DEBUG    Using proactor: IocpProactor
2020-08-26 02:52:17,407 asyncio      DEBUG    Using proactor: IocpProactor
